environments:
  default:
    values:
      - environments/default/values.yaml

repositories:
  - name: fsm-akka
    url: fsmakka.azurecr.io
    username: {{ .StateValues.username }}
    password: {{ .StateValues.password }}
    oci: true

releases:
  - name: foureyes
    namespace: fsmakka
    chart: oci://{{ .StateValues.url }}{{ .StateValues.path }}
    version: {{ .StateValues.version }}
    values:
      - values-test.yaml
